- job:
    name: ci-job-configs-sanity-check
    project-type: freestyle
    defaults: global
    properties:
        - authorization:
            anonymous:
                - job-read
                - job-extended-read
        - build-discarder:
            days-to-keep: 30
            num-to-keep: 30
    disabled: false
    node: master
    display-name: 'CI job configs sanity check'
    triggers:
        - gerrit:
            server-name: 'review.linaro.org'
            trigger-on:
                - patchset-created-event
            projects:
                - project-compare-type: 'PLAIN'
                  project-pattern: 'ci/job/configs'
                  branches:
                    - branch-pattern: 'master'
            silent-start: true
    wrappers:
        - timestamps
    builders:
        - shell: |
            #!/bin/bash -e
            echo "#${BUILD_NUMBER}-${GERRIT_PATCHSET_REVISION:0:8}" > ${WORKSPACE}/version.txt
        - build-name-setter:
            name: 'version.txt'
            file: true
        - shell: |
            #!/bin/bash

            set -e

            echo ""
            echo "########################################################################"
            echo "    Gerrit Environment"
            env |grep '^GERRIT'
            echo "########################################################################"

            rm -rf ${WORKSPACE}/*

            git clone -b ${GERRIT_BRANCH} --depth 2 https://review.linaro.org/${GERRIT_PROJECT}
            cd *
            git fetch https://review.linaro.org/${GERRIT_PROJECT} ${GERRIT_REFSPEC}
            git checkout -q FETCH_HEAD

            # FIXME run-jjb.py was meant to be used for deployment only
            # use JJB 'test' command instead of 'update' command
            sed -i "s|update|test|" run-jjb.py

            export GIT_PREVIOUS_COMMIT=$(git rev-parse HEAD~1)
            export GIT_COMMIT=${GERRIT_PATCHSET_REVISION}
            jenkins-job-builder --version
            python run-jjb.py
    publishers:
        - email:
            recipients: 'fathi.boudra@linaro.org'
