- job:
    name: trigger-ci-job-configs
    project-type: freestyle
    defaults: global
    properties:
        - authorization:
            linaro:
                - job-read
                - job-extended-read
        - build-discarder:
            days-to-keep: 30
            num-to-keep: 200
    disabled: false
    node: master
    display-name: 'CI job configs deployment'
    triggers:
        - gerrit:
            server-name: 'review.linaro.org'
            trigger-on:
                - change-merged-event
            projects:
                - project-compare-type: 'PLAIN'
                  project-pattern: 'ci/job/configs'
                  branches:
                    - branch-pattern: 'master'
            silent-start: true
    wrappers:
        - timestamps
        - credentials-binding:
            - text:
                credential-id: LAVA_USER
                variable: LAVA_USER
        - credentials-binding:
            - text:
                credential-id: LAVA_TOKEN
                variable: LAVA_TOKEN
        - credentials-binding:
            - text:
                credential-id: LT_QCOM_KEY
                variable: LT_QCOM_KEY
        - credentials-binding:
            - text:
                credential-id: AUTH_TOKEN
                variable: AUTH_TOKEN
    builders:
        - shell: |
            #!/bin/bash -e
            echo "#${BUILD_NUMBER}-${GERRIT_PATCHSET_REVISION:0:8}" > ${WORKSPACE}/version.txt
        - build-name-setter:
            name: 'version.txt'
            file: true
        - shell: |
            #!/bin/bash

            set -e

            echo ""
            echo "########################################################################"
            echo "    Gerrit Environment"
            env |grep '^GERRIT'
            echo "########################################################################"

            rm -rf ${WORKSPACE}/*

            git clone -b ${GERRIT_BRANCH} --depth 1 https://review.linaro.org/${GERRIT_PROJECT}
            cd *
            git fetch https://review.linaro.org/${GERRIT_PROJECT} ${GERRIT_REFSPEC}
            git checkout -q FETCH_HEAD

            export GIT_PREVIOUS_COMMIT=$(git rev-parse HEAD~1)
            export GIT_COMMIT=${GERRIT_PATCHSET_REVISION}
            jenkins-job-builder --version
            python run-jjb.py
    publishers:
        - email:
            recipients: 'fathi.boudra@linaro.org'
